"""•Upload-File:(backend)

Revision ID: 2467c23b2edb
Revises: 8dd8160a0407
Create Date: 2025-02-23 08:39:04.463069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2467c23b2edb'
down_revision = '8dd8160a0407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
